version: "3.8"
networks:
  rocketTeam-php-net:
    driver: bridge

services:

  mysql:
    image: mysql:latest
    container_name: rocketTeam-bbdd
    tty: true
    ports:
      - "3307:3306"
    volumes:
      - "./var/mysql/:/var/lib/mysql"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: bbddRocketTeam
      MYSQL_USER: miusuario
      MYSQL_PASSWORD: mipassword
    networks:
      - rocketTeam-php-net
   
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: rocketTeam-phpmyadmin
    restart: always
    ports:
      - "8080:80"
    environment:
      PMA_HOST: mysql
    networks:
      - rocketTeam-php-net

  apache:
    build: .
    container_name: rocketTeam-apache
    ports:
      - "3000:80"
    volumes:
      - "./var/php:/var/www/html"
    depends_on:
      - mysql
    networks:
      - rocketTeam-php-net
